Problem: PyPy build fails on Ubuntu Trusty/Xenial
Solution: add fallback for broken get_config_var which was fixed by:

https://bitbucket.org/pypy/pypy/pull-requests/608/adding-detection-of-gcc-to-sysconfig_pypy/diff

The default for CXX  is set by PyPy to c++ -pthread, so use the
same as a fallback if the function fails.

 Traceback (most recent call last):
   File "setup.py", line 130, in <module>
     os.environ["CXX"] = cxx + " " + cxx_flags
 TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'"